import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lucas Aquino - Fullstack Dev',
  description: 'Generated by create next app',
}

//<div className="w-100 h-[966px] bg-[url('/img/bg_home.png')]"></div>
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
